# on:
#   pull-requests:
#     branches:
#       - main
#     types:
#       - opened
#       - synchronize
#       - reopened
#   push:
#     branches:
#       - main

defaults:
  run:
    shell: bash

name: Script Upload

jobs:
  steps:
  - uses: 'actions/checkout@v3'

  - id: auth
    uses: google-github-actions/auth@v0.4.0
    with:
      workload_identity_provider: 'projects/1031638264464/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
      service_account: 'my-service-account@burner-ettreddy.iam.gserviceaccount.com'

  - id: 'upload-folder'
    uses: 'google-github-actions/upload-cloud-storage@v0'
    with:
      path: '../../linux-installer.txt'
      destination: 'test-script-upload'

